# .sops.yaml
keys:
  - &wsl age1m88wg7j8v430hkhwh5x486lv2hfpfzwyzy0ltqvtefj8kxdajyesncuyt8
  - &elitedesk age1w9ej6qutwnh4xfp5afjzy63ry09hmuyacg82t9327u5ph7j74qysqze7kr

creation_rules:
  - path_regex: secrets/.*$
    key_groups:
      - age:
          - *elitedesk
          - *wsl
